# version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning


  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./todo_project:/app
    ports:
    - "8000:8000"
    environment:
    - SECRET_KEY=test
    - DEBUG=True
    depends_on:
    - redis
  
  worker:
    build: .
    command: celery -A todo_project worker --loglevel=info
    depends_on:
    - redis
    - backend

  
  celery:
    build: .
    command: celery -A todo_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=todo_project.settings

  celery-beat:
    build: .
    command: celery -A todo_project beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=todo_project.settings