# version: "3.9"

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - app-network


  backend:
    build: .
    container_name: backend
    command: gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
    - ./todo_project:/app
    ports:
    - "8000:8000"
    environment:
    - SECRET_KEY=test
    - DEBUG=True
    depends_on:
    - redis
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - app-network


  worker:
    build: .
    command: celery -A todo_project worker --loglevel=info
    depends_on:
    - redis
    - backend

  
  
volumes:
  static_volume:
  media_volume:


networks:
  app-network:
    driver: bridge